using NUnit.Framework;
using NUnit.Framework.Legacy;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Text.RegularExpressions;
using System.Runtime.InteropServices;
using System.Timers;

namespace CodeChemSelenium.Tests
{
    public class CareersFunctionality
    {
        [Test]
        public void FunctionalityofHowweWork()
        {
            IWebDriver driver = new ChromeDriver();
            driver.Url = "https://codechem.com/";
            driver.Manage().Window.Maximize();
            Thread.Sleep(2000);
            driver.FindElement(By.LinkText("Careers")).Click();
            Thread.Sleep(2000);
            ClassicAssert.AreEqual("Job positions", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div[2]/h3")).Text);
            Thread.Sleep(2000);
            IJavaScriptExecutor js = (IJavaScriptExecutor)driver;
            js.ExecuteScript("window.scrollTo(0,600)");
            Thread.Sleep(1000);
            driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div[2]/div/a/div/div[2]/h6")).Click();
            Thread.Sleep(2000);
            js.ExecuteScript("window.scrollTo(0,400)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("No Particular Position", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div/div/div/h1")).Text);
            js.ExecuteScript("window.scrollTo(0,800)");
            Thread.Sleep(2000); ClassicAssert.AreEqual("About us", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div/h1")).Text);
            ClassicAssert.AreEqual("You will get", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[2]/h1")).Text);
            js.ExecuteScript("window.scrollTo(0,1200)");
            Thread.Sleep(2000);
            ClassicAssert.AreEqual("Extras", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[3]/h1")).Text);
            js.ExecuteScript("window.scrollTo(0,1500)");
            Thread.Sleep(2000);
            ClassicAssert.IsTrue(Regex.IsMatch(driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[4]/h1")).Text, "^Why work with us[\\s\\S]$"));
            driver.Navigate().Back();
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,1000)");
            Thread.Sleep(2000);
            driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div[2]/div/a[2]/div")).Click();
            Thread.Sleep(2000);
            js.ExecuteScript("window.scrollTo(0,700)");
            ClassicAssert.AreEqual("About the role", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div/h1")).Text);
            Thread.Sleep(2000);
            js.ExecuteScript("window.scrollTo(0,1400)");
            Thread.Sleep(1000);
            ClassicAssert.IsTrue(Regex.IsMatch(driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[2]/h1")).Text, "^What about you[\\s\\S]$"));
            Thread.Sleep(2000);
            js.ExecuteScript("window.scrollTo(0,1900)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("Nice to have", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[3]/h1")).Text);
            Thread.Sleep(2000);
            js.ExecuteScript("window.scrollTo(0,2500)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("About us", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[4]/h1")).Text);
            Thread.Sleep(2000);
            js.ExecuteScript("window.scrollTo(0,2800)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("The way we work", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[5]/h1")).Text);
            Thread.Sleep(2000);
            js.ExecuteScript("window.scrollTo(0,3400)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("You will get", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[6]/h1")).Text);
            Thread.Sleep(2000);
            js.ExecuteScript("window.scrollTo(0,3700)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("Extras", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[7]/h1")).Text);
            Thread.Sleep(2000);
            js.ExecuteScript("window.scrollTo(0,4000)");
            Thread.Sleep(1000);
            ClassicAssert.IsTrue(Regex.IsMatch(driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[8]/h1")).Text, "^Why work with us[\\s\\S]$"));
            Thread.Sleep(2000);
            driver.Navigate().Back();
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,1200)");
            Thread.Sleep(1000);
            driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div[2]/div/a[3]/div/div/h4")).Click();
            Thread.Sleep(2000);
            js.ExecuteScript("window.scrollTo(0,1200)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("QA Automation", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div/div/div/h1/span")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,2000)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("About the role", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div/h1")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,2500)");
            Thread.Sleep(1000);
            ClassicAssert.IsTrue(Regex.IsMatch(driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[2]/h1")).Text, "^What about you[\\s\\S]$"));
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,3000)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("About us", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[3]/h1")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,3400)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("The way we work", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[4]/h1")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,3800)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("Extras", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[6]/h1")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,4200)");
            Thread.Sleep(1000);
            driver.Navigate().Back();
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,1500)");
            Thread.Sleep(1000);
            driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div[2]/div/a[4]/div/div/h4")).Click();
            Thread.Sleep(1000);
            ClassicAssert.AreEqual(".NET Full Stack", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div/div/div/h1/span")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,1300)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("About the role", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div/h1")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,1600)");
            Thread.Sleep(1000);
            ClassicAssert.IsTrue(Regex.IsMatch(driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[2]/h1")).Text, "^What about you[\\s\\S]$"));
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,2000)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("About us", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[3]/h1")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,3000)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("The way we work", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[4]/h1")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,3200)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("You will get", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[5]/h1")).Text);
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("Extras", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[6]/h1")).Text);
            Thread.Sleep(1000);
            ClassicAssert.IsTrue(Regex.IsMatch(driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[7]/h1")).Text, "^Why work with us[\\s\\S]$"));
            Thread.Sleep(1000);
            driver.Navigate().Back();
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,1800)");
            driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div[2]/div/a[5]/div/div/h4")).Click();
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("Full Stack", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div/div/div/h1/span")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,900)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("About the role", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div/h1")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,1300)");
            Thread.Sleep(1000);
            ClassicAssert.IsTrue(Regex.IsMatch(driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[2]/h1")).Text, "^What about you[\\s\\S]$"));
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("About us", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[3]/h1")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,2100)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("The way we work", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[4]/h1")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,2800)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("You will get", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[5]/h1")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,3000)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("Extras", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[6]/h1")).Text);
            Thread.Sleep(1000);
            ClassicAssert.IsTrue(Regex.IsMatch(driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[7]/h1")).Text, "^Why work with us[\\s\\S]$"));
            Thread.Sleep(1000);
            driver.Navigate().Back();
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,2200)");
            Thread.Sleep(1000);
            driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div[2]/div/a[6]/div/div/h4")).Click();
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("DevOps", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div/div/div/h1/span")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,900)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("About the role", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div/h1")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,1200)");
            Thread.Sleep(1000);
            ClassicAssert.IsTrue(Regex.IsMatch(driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[2]/h1")).Text, "^What about you[\\s\\S]$"));
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("About us", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[3]/h1")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,2000)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("The way we work", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[4]/h1")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,2200)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("You will get", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[5]/h1")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,2500)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("Extras", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[6]/h1")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,2800)");
            Thread.Sleep(1000);
            ClassicAssert.IsTrue(Regex.IsMatch(driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[7]/h1")).Text, "^Why work with us[\\s\\S]$"));
            Thread.Sleep(1000);
            driver.Navigate().Back();
            js.ExecuteScript("window.scrollTo(0,2500)");
            Thread.Sleep(1000);
            driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div[2]/div/a[7]/div/div")).Click();
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("Machine Learning", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div/div/div/h1/span")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,700)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("About the role", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div/h1")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,1200)");
            Thread.Sleep(1000);
            ClassicAssert.IsTrue(Regex.IsMatch(driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[2]/h1")).Text, "^What about you[\\s\\S]$"));
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,1800)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("About us", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[3]/h1")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,2000)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("The way we work", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[4]/h1")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,2400)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("You will get", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[5]/h1")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,2700)");
            Thread.Sleep(1000);
            ClassicAssert.AreEqual("Extras", driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[6]/h1")).Text);
            Thread.Sleep(1000);
            js.ExecuteScript("window.scrollTo(0,3000)");
            Thread.Sleep(1000);
            ClassicAssert.IsTrue(Regex.IsMatch(driver.FindElement(By.XPath("//div[@id='__next']/div/div[2]/div/div[2]/div[7]/h1")).Text, "^Why work with us[\\s\\S]$"));
            Thread.Sleep(1000);
            driver.Navigate().Back();
            Thread.Sleep(2000);
            driver.Close();
        }
    }
}
